In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"/content/bbc_text_cls new.csv")

In [3]:
df.head()

text    labels percentage
0  Ad sales boost Time Warner profit\n\nQuarterly...  business        10%
1  Dollar gains on Greenspan speech\n\nThe dollar...  business        10%
2  Yukos unit buyer faces loan claim\n\nThe owner...  business        10%
3  High fuel prices hit BA's profits\n\nBritish A...  business        10%
4  Pernod takeover talk lifts Domecq\n\nShares in...  business        10%

In [4]:
df['labels'].value_counts()

labels
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [5]:
df.isnull().sum()

text          0
labels        0
percentage    0
dtype: int64

In [6]:
import re

In [7]:
def remove_tag(raw_text):
    cleaned_text = re.sub(r"\n", '', raw_text)
    return cleaned_text

In [8]:
df['text'] = df['text'].apply(remove_tag)

In [9]:
df

text    labels percentage
0     Ad sales boost Time Warner profitQuarterly pro...  business        10%
1     Dollar gains on Greenspan speechThe dollar has...  business        10%
2     Yukos unit buyer faces loan claimThe owners of...  business        10%
3     High fuel prices hit BA's profitsBritish Airwa...  business        10%
4     Pernod takeover talk lifts DomecqShares in UK ...  business        10%
...                                                 ...       ...        ...
2220  BT program to beat dialler scamsBT is introduc...      tech        10%
2221  Spam e-mails tempt net shoppersComputer users ...      tech        10%
2222  Be careful how you codeA new European directiv...      tech        10%
2223  US cyber security chief resignsThe man making ...      tech        10%
2224  Losing yourself in online gamingOnline role pl...      tech        10%

[2225 rows x 3 columns]

In [10]:
df['text'] = df['text'].apply(lambda x:x.lower())

In [11]:
df.head()

text    labels percentage
0  ad sales boost time warner profitquarterly pro...  business        10%
1  dollar gains on greenspan speechthe dollar has...  business        10%
2  yukos unit buyer faces loan claimthe owners of...  business        10%
3  high fuel prices hit ba's profitsbritish airwa...  business        10%
4  pernod takeover talk lifts domecqshares in uk ...  business        10%

In [14]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [15]:
df['text'] = df['text'].apply(lambda x:[item for item in x.split() if item not in stopwords]).apply(lambda x:" ".join(x))

In [46]:
df.head()

text    labels percentage
0  ad sales boost time warner profitquarterly pro...  business        10%
1  dollar gains greenspan speechthe dollar hit hi...  business        10%
2  yukos unit buyer faces loan claimthe owners em...  business        10%
3  high fuel prices hit ba's profitsbritish airwa...  business        10%
4  pernod takeover talk lifts domecqshares uk dri...  business        10%

## tfidf


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf= TfidfVectorizer()

In [22]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

x = df.iloc[: , 0:1]
y = df['labels']

encoder = LabelEncoder()
y = encoder.fit_transform(y)

x_trai  n, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=4)

x_train_tf = tfidf.fit_transform(x_train['text'])
x_test_tf = tfidf.transform(x_test['text'])

In [23]:
x_train_tf.shape

(1557, 26832)

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [26]:
model = RandomForestClassifier()
model.fit(x_train_tf, y_train)
y_pred = model.predict(x_test_tf)
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       163
           1       0.99      0.93      0.96       110
           2       0.97      0.93      0.95       132
           3       0.98      1.00      0.99       152
           4       0.96      0.98      0.97       111

    accuracy                           0.96       668
   macro avg       0.96      0.96      0.96       668
weighted avg       0.96      0.96      0.96       668

[[157   0   3   1   2]
 [  6 102   1   0   1]
 [  6   0 123   1   2]
 [  0   0   0 152   0]
 [  0   1   0   1 109]]
0.9625748502994012


# Other model try

In [27]:
x = df.iloc[: , 0:1]
y = df['labels']

In [28]:
x

text
0     ad sales boost time warner profitquarterly pro...
1     dollar gains greenspan speechthe dollar hit hi...
2     yukos unit buyer faces loan claimthe owners em...
3     high fuel prices hit ba's profitsbritish airwa...
4     pernod takeover talk lifts domecqshares uk dri...
...                                                 ...
2220  bt program beat dialler scamsbt introducing tw...
2221  spam e-mails tempt net shopperscomputer users ...
2222  careful codea new european directive could put...
2223  us cyber security chief resignsthe man making ...
2224  losing online gamingonline role playing games ...

[2225 rows x 1 columns]

In [29]:
y

0       business
1       business
2       business
3       business
4       business
          ...   
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: labels, Length: 2225, dtype: object

In [30]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [31]:
y=  encoder.fit_transform(y)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3 , random_state=4)

In [34]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((1557, 1), (1557,), (668, 1), (668,))

In [35]:
x_train

text
89    french wine gets 70m euro top-upthe french gov...
1219  iraq advice claim sparks new rowthe tories say...
186   bank payout pinochet victimsa us bank said don...
2090  year search became personalthe odds fire brows...
908   howard rebuts asylum criticismstory leader mic...
...                                                 ...
456   germany calls eu reformgerman chancellor gerha...
1921  mobiles rack 20 years usemobile phones uk cele...
709   celebrities get stay jungleall four contestant...
174   french consumer spending risingfrench consumer...
1146  brown blair face new rift claimsfor umpteenth ...

[1557 rows x 1 columns]

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [37]:
x_train1 = cv.fit_transform(x_train['text']).toarray()
x_test1 = cv.transform(x_test['text']).toarray()

In [38]:
x_train1.shape , x_test1.shape

((1557, 26832), (668, 26832))

In [47]:
from sklearn.naive_bayes import MultinomialNB , BernoulliNB

In [40]:
def model(model):
  model.fit(x_train1, y_train)
  y_pred = model.predict(x_test1)
  print(classification_report(y_test , y_pred))
  print(confusion_matrix(y_test , y_pred))
  print(accuracy_score(y_test , y_pred))

In [41]:
model(MultinomialNB())

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       163
           1       0.98      0.94      0.96       110
           2       0.95      0.98      0.96       132
           3       1.00      1.00      1.00       152
           4       0.94      0.99      0.96       111

    accuracy                           0.97       668
   macro avg       0.97      0.97      0.97       668
weighted avg       0.97      0.97      0.97       668

[[156   1   3   0   3]
 [  0 103   4   0   3]
 [  2   0 129   0   1]
 [  0   0   0 152   0]
 [  0   1   0   0 110]]
0.9730538922155688


In [43]:
model(BernoulliNB())

              precision    recall  f1-score   support

           0       0.94      0.99      0.96       163
           1       0.99      0.95      0.97       110
           2       0.96      0.92      0.94       132
           3       0.99      1.00      1.00       152
           4       0.97      0.96      0.97       111

    accuracy                           0.97       668
   macro avg       0.97      0.97      0.97       668
weighted avg       0.97      0.97      0.97       668

[[162   0   1   0   0]
 [  1 104   3   0   2]
 [  8   0 122   1   1]
 [  0   0   0 152   0]
 [  2   1   1   0 107]]
0.968562874251497
